### ISSUE TITLE
NC19 Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by MeiRos** [nextcloud/3rdparty#431] opened 2020-04-12 16:31 UTC
I installed Nextcloud 19 beta 2. After that I don't see any old errors from compiler.php. (Nextcloud 18) There are two new errors in the nextcloud.log. And when the errors shows up those comes many times in a row

```
Trying to access array offset on value of type null at /home/nginx/domain.net/public/3rdparty/scssphp/scssphp/src/Compiler.php#6189
Trying to access array offset on value of type null at /home/nginx/domain.net/public/3rdparty/scssphp/scssphp/src/Compiler.php#2716
```

I have CentOS 7, **PHP 7.4.4**, 10.4.12-MariaDB, nginx/1.17.9

**Comment by J0WI** [comment] 2020-04-16 13:36
Duplicate of https://github.com/nextcloud/server/issues/18996

**Closed by J0WI** 2020-04-16 13:36 UTC

**Comment by MeiRos** [comment] 2020-04-16 14:20
It's not a duplicate, I think. Error lines are different.
I also had "Error PHP Trying to access array offset on value of type null at /var/www/nextcloud/3rdparty/leafo/scssphp/src/Compiler.php#**5230**" when I had NC18.

But now with NC19 the errors are "Trying to access array offset on value of type null at /home/nginx/domain.net/public/3rdparty/scssphp/scssphp/src/Compiler.php#**6189**
Trying to access array offset on value of type null at /home/nginx/domain.net/public/3rdparty/scssphp/scssphp/src/Compiler.php#**2716**". 

If this is duplicate, why the errors are different than before?

**Comment by MeiRos** [comment] 2020-04-16 19:38
Ok. Let's see what happens. Hopefully you are right.
