### ISSUE TITLE
NC18RC1, php7.4 report

### ISSUE THREAD

**Issue by jookk** [nextcloud/3rdparty#376] opened 2020-01-06 08:45 UTC
The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence at /var/www/nextcloud/3rdparty/sabre/vobject/lib/Recur/RRuleIterator.php#423

The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence at /var/www/nextcloud/3rdparty/sabre/vobject/lib/Recur/RRuleIterator.php#357

nginx 1.17.7
php7.4-fpm
debian 10

**Comment by jookk** [comment] 2020-01-08 11:16
Trying to access array offset on value of type null at /var/www/nextcloud/3rdparty/leafo/scssphp/src/Compiler.php#5230

**Comment by J0WI** [comment] 2020-01-20 14:58
See also https://github.com/nextcloud/server/issues/18996

**Comment by J0WI** [comment] 2020-04-16 13:41
Duplicate of https://github.com/nextcloud/server/issues/16574

**Closed by J0WI** 2020-04-16 13:41 UTC
